variables:
  uiSource: "src/ui"
  uiBuild: "$(uiSource)/build"

pool:
  name: Default
  demands:
    - agent.name -equals ALPHA


steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      pushd $(uiSource)
      npm install
      npm run build
      npm publish
      popd
    displayName: "Build UI"

  # - task: ArchiveFiles@2
  #   displayName: Archive
  #   inputs:
  #     rootFolderOrFile: "$(uiBuild)"
  #     includeRootFolder: false
  #     archiveType: "zip"
  #     archiveFile: "$(Build.ArtifactStagingDirectory)/ui-$(Build.BuildId).zip"
  #     replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
